import { readNetwork } from "./functions/read-network.js";
import { diagnose } from "./functions/diagnose.js";
import { calculateNetworkMetrics } from "./functions/calculate-metrics.js";
import { generateAlerts } from "./functions/generate-alerts.js";
import { formatHeader } from "./report/format-header.js";
import { formatMetrics } from "./report/format-metrics.js";
import { formatDiagnoses } from "./report/format-diagnoses.js";
import { formatAlerts } from "./report/format-alerts.js";

// Get file path from command-line argument
const filePath = process.argv[2];

if (!filePath) {
  console.error("Error: no file path provided.");
  console.error("Usage: pnpm run:audit <path-to-json>");
  console.error("Example: pnpm run:audit ./data/network.json");
  process.exit(1);
}

try {
  // 1. Load data
  const network = readNetwork(filePath);

  // 2. Process data
  const diagnoses = network.clinics.map((clinic) => diagnose(clinic));
  const metrics = calculateNetworkMetrics(network.clinics);
  const alerts = generateAlerts(diagnoses);

  // 3. Format report
  const report =
    formatHeader(network) +
    formatMetrics(metrics) +
    formatDiagnoses(diagnoses) +
    formatAlerts(alerts) +
    `
═════════════════════════════════════════════
    Generated by GN1 Quick Audit v1.0.0
═════════════════════════════════════════════
`;

  // 4. Output
  console.log(report);
} catch (error) {
  if (error instanceof Error) {
    console.error(`Audit failed: ${error.message}`);
  } else {
    console.error("Audit failed with unknown error.");
  }
  process.exit(1);
}